language: node_js

node_js: stable

install:
  - npm install
  - npm install hexo-theme-next@8.2.2 --save
  - npm install hexo-generator-searchdb --save
  - npm install hexo-generator-sitemap --save
  - npm install hexo-generator-baidu-sitemap --save
  - npm install hexo-filter-flowchart --save
  - npm install hexo-filter-sequence --save
  - npm install valine --save
#  - gem install faraday activesupport sitemap-parser

#before_script:
#  - node imgUpdate.nodejs

script:
  - hexo cl
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "iexxk"
  - git config user.email "xuan.fong1@163.com"
  - git add .
  - git commit -m "update"
  - git push --force --quiet "https://${BLOG_GITHUB}@${GH_REF}" master:master
  - git push --force --quiet "https://DzuFKhZbCW:${BLOG_CODING}@${CD_REF}" master:master
#  - ruby comment.rb ${GITMENT}

branches:
  only:
    - hexo
env:
 global:
   - GH_REF: github.com/iexxk/iexxk.github.io.git
   - CD_REF: e.coding.net/exxk/exxk.coding.me.git
