[build]
  base    = "."
  publish = "public/"
  command = "npm install && npm install hexo-generator-searchdb --save && npm install hexo-generator-sitemap --save && npm install hexo-generator-baidu-sitemap --save && npm install hexo-filter-mermaid-diagrams --save && hexo cl && hexo g"